### ISSUE TITLE
Create a settings page

### ISSUE THREAD

**Issue by okennedy** [VizierDB/vizier-scala#164]
A new page for configuring vizier-specific settings would be helpful:

- [x] Configure [Default Google Maps API key](https://github.com/VizierDB/vizier-scala/blob/v2.0/vizier/src/info/vizierdb/Config.scala#L39)
- [x] Configure [Default OSM Server](https://github.com/VizierDB/vizier-scala/blob/v2.0/vizier/src/info/vizierdb/Config.scala#L44)
- [x] Configure/Set Up project-specific PyEnv (#58 )
- [x] Configure/Set up PIP packages (#13 )
- [ ] Inject Maven artifacts (#94 )
- [x] Enable/disable notifications (#39 )

Suggested approach: Start with the [UI main](https://github.com/VizierDB/vizier-scala/blob/v2.0/vizier/ui/src/info/vizierdb/ui/Vizier.scala) and add a new [html page](https://github.com/VizierDB/vizier-scala/tree/v2.0/vizier/ui/html) with config options on it.

**Comment by okennedy** [comment]
![image](https://user-images.githubusercontent.com/3641553/178130461-7f7e38fb-1223-41a8-b09a-824e07269582.png)

**Comment by okennedy** [comment]
![image](https://user-images.githubusercontent.com/3641553/178131027-3a59bfe6-829f-4560-a54e-e142fea0ecf3.png)

**Comment by okennedy** [comment]
![image](https://user-images.githubusercontent.com/3641553/180565392-035d153c-58c2-4f82-ad29-88ea575c01b4.png)

**Comment by okennedy** [comment]
Idea: grey-out the "Save" button unless there are pending changes.

**Comment by okennedy** [comment]
Closing, since the maven artifacts issue is its own thing now.
